In [2]:
import numpy as np
import scipy as spy
from scipy.special import jv
import numpy as np
from scipy.optimize import minimize_scalar, minimize
from scipy.optimize import brentq
from scipy.interpolate import interp1d

# define the x value (in our case 0 t0 20 is sufficient)
step = 0.001
x = np.arange(0,20,step)
m = [0, 1, 2, 3,4]
y = np.array([])
for i in m:
    y = np.append(y, jv(i, x))
# jv(v, x) is the Bessel function of the v-th order.

# Now we calculate the derivative j’(v, x)
J = y.reshape(len(m), x.size)
dJdx = np.array([])
for row in J:
    dJdx = np.append(dJdx, np.gradient(row, x))
dJdx = dJdx.reshape(len(m), x.size)

# find the roots
def roots(x, y):
    f = interp1d(x, y, kind='linear', fill_value='extrapolate', assume_sorted=True)
    s = np.signbit(y)
    idx = np.flatnonzero(s[1:] != s[:-1])
    r = [brentq(f, x[i], x[i + 1]) for i in idx]
    exact = np.array([])
    return np.sort(np.unique(np.concatenate([exact, np.array(r)])))

for i in range(0,5):
    print(roots(x, dJdx[i]))


[ 3.83170604  7.01558671 10.17346816 13.32369196 16.47063007 19.61585852]
[ 1.8411838   5.33144282  8.5363164  11.70600492 14.86358865 18.01552788]
[ 3.05423689  6.70613322  9.96946785 13.17037088 16.34752234 19.51291279]
[ 4.20118888  8.01523662 11.34592433 14.5858483  17.78874788]
[ 5.31755304  9.2823963  12.68190846 15.96410705 19.19602881]
